swagger: "2.0"
info:
  version: "0.0.1"
  title: Project tracker
# replaced during gulp compileSwagger script to localhost: + PORT
host: localhost:3000
basePath: "/"
schemes:
  # tip: remove http to make production-grade
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /user/status:
    x-swagger-router-controller: "user.controller"
    post:
      operationId: status
      responses:
        "200":
          description: Success
          schema:
            $ref: "definitions.yaml#/MessageResponse"
        default:
          description: Error
          schema:
            $ref: "definitions.yaml#/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw

