version: 1.0.{build}

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - development
  - master

skip_tags: true

environment:
  matrix:
    - nodejs_version: "6"

platform:
  - x64

install:
  - cmd: npm run-script prebuild

build: off

cache:
  - C:\Users\appveyor\AppData\Roaming\npm\node_modules -> package.json  # global npm modules
  - C:\Users\appveyor\AppData\Roaming\npm-cache -> package.json         # npm cache
  - node_modules -> package.json
  - public\vendors -> bower.json

deploy: off

notifications:
- provider: GitHubPullRequest
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true