swagger: '2.0'
info:
  version: 0.0.1
  title: Project tracker
host: 'localhost:3001'
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /user/status:
    x-swagger-router-controller: user.controller
    post:
      operationId: status
      responses:
        '200':
          description: Success
          schema:
            required:
              - message
            properties:
              message:
                type: string
        default:
          description: Error
          schema: &ref_0
            required:
              - message
            properties:
              message:
                type: string
  /history:
    x-swagger-router-controller: history.controller
    get:
      operationId: all
      responses:
        '200':
          description: A list of history items
          schema:
            type: array
            items:
              properties:
                id:
                  type: string
                description:
                  type: string
        default:
          description: Error
          schema: *ref_0
    delete:
      operationId: delete
      responses:
        default:
          description: Error
          schema: *ref_0
  /swagger:
    x-swagger-pipe: swagger_raw
