swagger: '2.0'
info:
  version: 0.0.1
  title: Hello World App
host: 'localhost:3001'
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /user/status:
    x-swagger-router-controller: user.controller
    post:
      operationId: status
      responses:
        '200':
          description: Success
          schema:
            required:
              - message
            properties:
              message:
                type: string
        default:
          description: Error
          schema:
            required:
              - message
            properties:
              message:
                type: string
  /swagger:
    x-swagger-pipe: swagger_raw
